Don't ask why this exists

Also configure everything in creds.py before running main.
